### ISSUE TITLE
object not serializable

### ISSUE THREAD

**Issue by qazmichaelgw** [unicredit/hbase-rdd#11]
When I read the rdd from hbase, like

    val rddRes = sc.hbase[String](table, columns)
    rddRes.collect()

it seems that when I use collect operation, it will raise an org.apache.spark.SparkException.
the error message like this:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0.0 in stage 4.0 (TID 8) had a not serializable result: scala.collection.immutable.MapLike$$anon$2 Serialization stack:

**Comment by andreaferretti** [comment]
I think this should be related to [this fix](https://github.com/unicredit/hbase-rdd/commit/242de2b6902243f60984a876b920a978a0fad4f6). It is a known bug in Scala that a few operations on `Map` actually return a `MapLike`, and the latter is not serializable (`mapValues` being a typical example).

If I recalll correctly, `toMap` was added in that context exactly for the same issue. Will investigate, it should be more or less the same

**Comment by andreaferretti** [comment]
It could be a missing `toMap` [here](https://github.com/unicredit/hbase-rdd/blob/master/src/main/scala/unicredit/spark/hbase/HBaseReadSupport.scala#L138) (and in similar places)

**Comment by fralken** [comment]
Indeed, this issue was only for the case where you define a set of column families

    sc.hbase[String](table, Set(...))

In this case we executed a mapValues transformation which returns a MapLike, which is not serializable, instead of a (serializable) Map.
