### ISSUE TITLE
need help on write hfile

### ISSUE THREAD

**Issue by qhzhou** [unicredit/hbase-rdd#12]
Hi, I am not using this project, however I am facing the situation that I need to write rdd to hfile, then bulk load to htable.
when I try to do a little demo, I met the following error:

Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0.0 in stage 1.0 (TID 2) had a not serializable result: org.apache.hadoop.io.ImmutableBytesWritable
Serialization stack:
	- object not serializable (class: org.apache.hadoop.io.ImmutableBytesWritable)
	- element of array (index: 0)
	- array (class [Ljava.lang.Object;, size 45)
	- field (class: scala.Tuple3, name: _3, type: class java.lang.Object)
	- object (class scala.Tuple3, (0,45,[Ljava.lang.Object;@55fd571a))
	- element of array (index: 0)
	- array (class [Lscala.Tuple3;, size 1)

and here is the code snippet:
https://gist.github.com/qhzhou/40c6dc4d8d4143fbbb60

My question is that:
should I wrap the ImmutableBytesWritable to a Serializable in order to run the job?

will appreciate if anyone can help, thank you in advance

**Comment by fralken** [comment]
I'm sorry but we can give support only to users of our library.

Anyway, you can try to map to ImmutableBytesWritable just before the call to saveAsNewAPIHadoopFile (that is, after the sortByKey)

**Comment by qhzhou** [comment]
Thank you, I have managed to map to ImmutableBytesWritable after sortByKey, and it worked.
It looks like that sortByKey will shuffle the data through workers.
Anyway thank you so much for the tips.

**Comment by fralken** [comment]
Yes, of course sortByKey shuffles among workers, that's why the key must be serializable.
