### ISSUE TITLE
sbt dependency

### ISSUE THREAD

**Issue by qazmichaelgw** [unicredit/hbase-rdd#13]
When I use the build.sbt. I got some strange problem. 
Error:(117, 19) value getInstance is not a member of object org.apache.hadoop.mapreduce.Job
    val job = Job.getInstance(conf)
                  ^
However, getInstance is really a method of Job. I spend a lot of time with the sbt dependencies. Is any one have some idea about this? Thanks a lot!

**Comment by fralken** [comment]
Well, maybe in your dependencies you have different versions of the same package. Clean up your dependencies and try again. You can start again from our build.sbt

**Comment by qazmichaelgw** [comment]
After start again, I still get another problem. 
Error:(75, 20) value getColumnLatestCell is not a member of org.apache.hadoop.hbase.client.Result
            result.getColumnLatestCell(cf.getBytes, column.getBytes)
                   ^
My build.sbt is like this, and my sbt version is 0.13.8.
It is quite strange.
version := "0.0.1"

scalaVersion := "2.10.4"

scalacOptions ++= Seq(
  "-deprecation",
  "-feature",
  "-language:postfixOps",
  "-language:implicitConversions",
  "-language:reflectiveCalls"
)

resolvers ++= Seq(
  "Cloudera repos" at "https://repository.cloudera.com/artifactory/cloudera-repos",
  "Cloudera releases" at "https://repository.cloudera.com/artifactory/libs-release",
  "nexus" at "http://repos.6estates.com/nexus/content/groups/public/"
)

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "1.2.0" % "provided",
  "org.apache.hbase" % "hbase-common" % "0.98.6-cdh5.3.1" % "provided",
  "org.apache.hbase" % "hbase-client" % "0.98.6-cdh5.3.1" % "provided",
  "org.apache.hbase" % "hbase-server" % "0.98.6-cdh5.3.1" % "provided",
  "com.framework" % "framework-db-hbase" % "1.1.0-SNAPSHOT" % "compile",
  "org.deeplearning4j" % "deeplearning4j-core" % "0.0.3.3.3.alpha1" % "compile",
  "org.deeplearning4j" %  "deeplearning4j-nlp"  % "0.0.3.3.3.alpha1" % "compile"
    exclude("javax.jms", "jms") exclude("com.sun.jdmk", "jmxtools") exclude("com.sun.jmx", "jmxri"),
  "org.nd4j"           %  "nd4j-jblas"          % "0.0.3.5.5.3" % "compile"
) 

publishMavenStyle := true

pomIncludeRepository := { x => false }

**Comment by fralken** [comment]
Please don't use this space as an help support for generic Scala programming. We can provide help only for our project.

Again your problem is a dependency conflict and you can solve it by carefully analyzing your dependencies.
