### ISSUE TITLE
saveAsNewAPIHadoopDataset hangs under standalone mode

### ISSUE THREAD

**Issue by gycrazydog** [unicredit/hbase-rdd#19]
Hi, my Spark program with this library hangs at following step:

saveAsNewAPIHadoopDataset at HBaseWriteSupport.scala:92

I'm using Spark 1.2.2 and hbase 0.98.15. The program works fine under local mode, but hangs at this step once I give it a master url.

Anybody have encoutered this before or have any clue about the issue?

Thanks,
Canran

**Comment by fralken** [comment]
Can you give some more information on your configuration? It is difficult to help you otherwise.

**Comment by gycrazydog** [comment]
Hi I think it's my own mistake, the program cannot find hbase-site.xml.

It's working now after I specified the zookeeper quorum explicitly in code.

Thanks for your help still.

**Comment by fralken** [comment]
Great!
