### ISSUE TITLE
The readme about delete operation may has a false

### ISSUE THREAD

**Issue by zzz24512653** [unicredit/hbase-rdd#24]
In readme, I think there is a mistake of Deleting from HBase. 

val cf = "cf1"
val headers: Seq[String] = ...
val rdd: RDD[String] = ...
rdd.toHBase(table, cf, headers)

I use it to delete, it didn't work, but when I use rdd.deleteHBase(table, cf, Set(headers)), it worked.

**Comment by fralken** [comment]
Yes, you are right. Documentation was incorrect. Now fixed.
Thanks a lot!
