### ISSUE TITLE
Support Array[Byte] as row keys

### ISSUE THREAD

**Issue by wobu** [unicredit/hbase-rdd#26]
Is there a reason why you enforce `String` as row key type?

We are using normal `Long` and `Integer` as row key.

**Comment by fralken** [comment]
Mainly for simplicity. It was enough for our use cases to deal with row keys and qualifier as strings.

We could use generics for row keys and qualifiers as well, providing implicit converters to Array[Byte].

**Comment by fralken** [comment]
@wobu in branch generic-kq I implemented generic types for row keys and qualifiers, too.
You can test it and let me know.

**Comment by wobu** [comment]
i cannot replace fast the current implementation with that, but i will have a look onto it and give it a quick try.

**Comment by wobu** [comment]
tested reading via spark-shell -> worked

**Comment by fralken** [comment]
Implemented in version 0.8.0
