### ISSUE TITLE
How does this project compare to Hortonworks SparkOnHBase?

### ISSUE THREAD

**Issue by dalamar66** [unicredit/hbase-rdd#30]
I've seen that Spark-on-HBase from Hortonworks also support bulk reads/writes, is there any clear benefit of using one over the other?

Not sure if this is the correct place to ask this, do you have a group or forum to discuss?

**Comment by fralken** [comment]
I don't know Hortonworks' Spark-on-HBase, but from their documentation I see that it works with DataFrames, while our library works with RDDs.

As for the bulk feature, we implement bulk import as described in the [HBase Book](http://hbase.apache.org/book.html#arch.bulk.load). This is an efficient way to import data to a HBase table, but out-of-the-box you need to run a MapReduce job to prepare data, and than call the "completebulkload" utility to load into HBase.
With our library you can do this in Spark with just one method call.
