### ISSUE TITLE
Too many open files exception on bulk load

### ISSUE THREAD

**Issue by johngouf** [unicredit/hbase-rdd#4]
When I try to use the bulk load I get this exception.
I know that I need to increase ulimit, but I have no root access to the machine.
Is there a workaround for this?

Thanks a lot!

**Comment by fmontecuccolideglierri** [comment]
Can you provide a stack trace and some info on what you are trying to achieve? (e.g. hbase configuration, size of your dataset, number of regions of your table...) Thanks

**Comment by fralken** [comment]
I don't know if it can be related to this problem, but starting from version 0.5.0 it is possible to set the number of hfiles per region, which now defaults to 1. Previously it was fixed to 32.
