### ISSUE TITLE
Add support for JavaRDD

### ISSUE THREAD

**Issue by btiernay** [unicredit/hbase-rdd#5]
Hi, I'm not sure if this is currently possible, but I couldn't figure out a way to achieve it. I think it would be tremendously useful however.

At the very least, perhaps add a note to the README for future Java readers.

Thanks!

**Comment by andreaferretti** [comment]
Yes, we currently do not support Java.

I don't think we will be able to put the effort to add support for it, as we do not use Java. We would be glad to accept pull requests, though. ;-)
